[build]
builder = "NIXPACKS"
buildCommand = "mvn clean package -DskipTests"

[deploy]
startCommand = "java -jar /usr/local/tomcat/bin/bootstrap.jar"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
